version: "3.3"
services:
 mongol:
  image: mongo:6-jammy
  container_name: mongol
  ports:
    - 27017:27017
  volumes:
    - oca-db:/data/db
  networks:
    - oca
  restart: unless-stopped
  
 oca-api:
  image: nachocode/oca:api
  container_name: oca-api
  environment:
    - IP_ADDR=0.0.0.0
    - PORT=5000
    - RELOAD=0
    - MONGO_IP_ADDR=mongol
    - LOG_DEBUG=1
  ports:
    - 5000:5000
  networks:
    - oca
  volumes:
    - "/log:/log"
networks:
  oca:
volumes:
  oca-db:
    external: true
