services:
  mongo1:
    image: nachocode/mongox:n1
    container_name: mongo1
    ports:
      - 27017:27017
    networks:
      - mictlanx
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: oca
    #   MONGO_INITDB_ROOT_PASSWORD: d22a75e9e729debc
    volumes:
      - mongo1-db:/data/db
      - ./configs/mongo1.conf:/etc/mongo/mongod.conf
      - ./mongokey:/data/key/mongokey
    # command: mongod 
    # --config /etc/mongo/mongod.conf
    # command: >
    #   mongod --bind_ip_all --replSet rs0
    restart: unless-stopped

  mongo2:
    # image: mongo:6-jammy
    image: nachocode/mongox:n2
    container_name: mongo2
    ports:
      - 27018:27017
    networks:
      - mictlanx
    volumes:
      - mongo2-db:/data/db
      - ./configs/mongo2.conf:/etc/mongo/mongod.conf
      - ./mongokey:/data/key/mongokey
        #- ./mongo-key:/data/key
    # command: >
      # mongod --bind_ip_all --replSet rs0
    restart: unless-stopped

  mongo3:
    # image: mongo:6-jammy
    image: nachocode/mongox:n3
    container_name: mongo3
    ports:
      - 27019:27017
    networks:
      - mictlanx
    volumes:
      - mongo3-db:/data/db
      - ./configs/mongo3.conf:/etc/mongo/mongod.conf
      - ./mongokey:/data/key/mongokey
    # command: >
      # mongod --bind_ip_all --replSet rs0
    restart: unless-stopped



networks:
  mictlanx:

volumes:
  mongo1-db:
  mongo2-db:
  mongo3-db:
